Added header back icon , refactor Icons
ChildMindInstitute/mindlogger-app-refactor pull request #10
Opened 2023-01-09 11:28 UTC by vmkhitaryanscn

2023-01-09 13:28 UTC, BamMironov requested changes

2023-01-09 13:28 UTC, BamMironov commented on src/shared/ui/Icons.tsx
> +  <AntDesign name="close" color={color} size={size} />
Please destruct props here for sake of simplicity.
```
const CloseIcon: FC<IconProps> = props => (
  <AntDesign name="close" {...props} />
```

2023-01-09 15:57 UTC, anq83 approved these changes

2023-01-10 06:55 UTC, BamMironov approved these changes

2023-01-10 06:56 UTC, merged