Feat/activity SLIDER item contract
ChildMindInstitute/mindlogger-app-refactor pull request #116
Opened 2023-03-31 08:41 UTC by vmkhitaryanscn

2023-03-31 10:39 UTC, anq83 requested changes

2023-03-31 10:39 UTC, anq83 commented on src/shared/ui/survey/Slider/SurveySlider.tsx
> +        defaultValue={[initialValue]}
If you set min-max in the test dto lets say 10-20
then slider is absend when start activity

2023-03-31 10:39 UTC, anq83 commented on src/shared/ui/survey/Slider/SurveySlider.tsx
> +        {items.map((value, index) => {
Please fill necessary values into items array (i.o 1) and use value, remove index

2023-03-31 10:58 UTC, anq83 approved these changes

2023-03-31 14:25 UTC, BamMironov requested changes

2023-03-31 14:25 UTC, BamMironov commented on src/features/pass-survey/ui/ActivityItem.tsx
> +            onChange={() => console.log('changed')}
Add onResponse to onChange prop

2023-03-31 14:25 UTC, BamMironov commented on src/shared/ui/survey/Slider/SurveySlider.tsx
> +  }
Please use `Array.from` instead. Something  like this:
```
Array.from(
    { length: maxValue - minValue },
    (_, index) => index + minValue,
 )
```

2023-04-03 09:32 UTC, BamMironov approved these changes

2023-04-03 09:41 UTC, merged