M2-1618: Add notification backend logs
ChildMindInstitute/mindlogger-app-refactor pull request #185
Opened 2023-04-29 10:22 UTC by anq83

2023-05-02 14:28 UTC, BamMironov requested changes

2023-05-02 14:32 UTC, BamMironov requested changes

2023-05-02 14:32 UTC, BamMironov commented on src/features/tap-on-notification/model/hooks/useOnNotificationTap.ts
> +import { ActivityGroupsBuildManager } from '@app/widgets/activity-group/model/services';
We can not import widget into feature

2023-05-02 14:55 UTC, anq83 commented on src/entities/notification/lib/services/NotificationsLogger.ts
> +        ? [{}]
This is backend requirement to receive an empty object in such cases

2023-05-03 16:19 UTC, BamMironov approved these changes

2023-05-10 10:11 UTC, merged