Added Stability tracker touch version, added gyroscope pipeline item
ChildMindInstitute/mindlogger-app-refactor pull request #239
Opened 2023-06-14 09:39 UTC by vmkhitaryanscn

2023-06-14 11:33 UTC, BamMironov commented on src/entities/gyroscope/lib/utils/calculations.ts
> +export const generateTargetTrajectory = (
Please put an empty line between imports and exports

2023-06-14 11:33 UTC, BamMironov commented on src/entities/gyroscope/lib/utils/calculations.ts
> +  const LV = currentLambda + (currentTs / 1000) * lambdaSlope;
Please rename it to lambdaValue

2023-06-14 11:55 UTC, BamMironov requested changes

2023-06-14 11:55 UTC, BamMironov commented on src/entities/stabilityTracker/lib/constants/index.ts
> +export const center = PLAYGROUND_WIDTH / 2;
Please use upper case when naming variables

2023-06-14 11:55 UTC, BamMironov commented on src/entities/stabilityTracker/lib/hooks/useAnimation.ts
> +  const animate = (timeStamp: number) => {
please put an empty line between the variable and the function expression

2023-06-21 07:53 UTC, BamMironov requested changes

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/lib/utils/calculations.ts
> +export const generateTargetTrajectory = (
Please put an empty line between imports and exports

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/lib/types/index.ts
> +  // maxLambda: number;
Why did you comment it?

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/lib/utils/calculations.ts
> +  userPos: Coordinate,
Please rename t stimulusPosition and userPosition for more clarity

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +  );
There is no need to use useMemo here

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +  const [deltaNumber, setDeltaTime] = useState<number>(0);
I just found out that we have a special hook for this purpose called "useForceUpdate". Please use it

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +  maxLambda: unknown | number;
I think the type for maxLambda should be just number

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +  const lambdaLimit = IS_TRIAL ? 0 : 0.3 * maxLambda;
Since maxLambda is number there is no need to add the ts-ignore directive

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +    responses.current.map((response: Response) => {
Please use forEach instead of map here

2023-06-21 07:53 UTC, BamMironov commented on src/entities/stabilityTracker/ui/StabilityTrackerItem.tsx
> +      userPos: [userPosition.current[1] / PANEL_RADIUS - 1],
Please rename stimPos and userPos here also

2023-06-21 07:53 UTC, BamMironov commented on src/shared/ui/MarkdownView.tsx
> +export default MarkdownView; // @todo was the memo a good idea?
We will see if we face performance issues

2023-06-21 08:25 UTC, anq83 requested changes

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/lib/utils/calculations.ts
> +  currentTs: number,
what is Ts? please rename

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/lib/utils/calculations.ts
> +  lambdaVal: number,
what is Val ? please rename

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/lib/types/index.ts
> +  stimPos: number[];
Pos is Position? Please, rename, this is not C++

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +    // appletId,
remove please

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +  // const [tickNumber, setTickNumber] = useState(0);
remove please

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +  const baseOri = useRef();
what is Ori? can we rename?

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +    onComplete(['atata']);
The below - looks like temp code.
Can we remove it? Or change somehow to get it prepared for merge to dev

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +      (delta[1] * deltaTime) / 1000 + circlePosition.current[1];
Why there's circlePosition.current[1] over the code, can we handle somehow? Not clear what is index 1

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +    const newCirclePositionY =
new line, please

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +    const delta = computeDxDt(
Can we rename computeDxDt? Not cleat what is DxDt

2023-06-21 08:25 UTC, anq83 commented on src/entities/stabilityTracker/ui/StabilityTracker.gyro.backup.js
> +    if (isMoving) {
Looks like code in old app

2023-06-28 10:51 UTC, BamMironov approved these changes

2023-07-04 14:01 UTC, anq83 approved these changes

2023-07-04 14:02 UTC, merged