M2 2188 drawing item
ChildMindInstitute/mindlogger-app-refactor pull request #258
Opened 2023-06-27 11:27 UTC by DimitrySakalouski

2023-06-28 08:30 UTC, BamMironov requested changes

2023-06-28 08:30 UTC, BamMironov commented on src/shared/ui/ScrollableContent.tsx
> +  }, [scrollContentHeight, windowHeight]);
There is no need to use useMemo here

2023-06-28 11:20 UTC, anq83 approved these changes

2023-06-29 10:56 UTC, BamMironov approved these changes

2023-06-29 11:02 UTC, merged