Fixed applets refreshing bug, when no internet connection available
ChildMindInstitute/mindlogger-app-refactor pull request #271
Opened 2023-07-06 10:20 UTC by vmkhitaryanscn

2023-07-06 11:52 UTC, anq83 requested changes

2023-07-06 11:52 UTC, anq83 commented on src/features/applets-refresh/ui/AppletsRefresh.tsx
> +  const [appletsRefreshing, setAppletsRefreshing] = useState(false);
I'll have to check this fix

2023-07-07 08:45 UTC, BamMironov approved these changes

2023-07-10 11:30 UTC, anq83 requested changes

2023-07-10 11:30 UTC, anq83 commented on src/features/applets-refresh/ui/AppletsRefresh.tsx
> +  const [appletsRefreshing, setAppletsRefreshing] = useState(false);
I've checked on ios simulator. The spenner is not shown now, when pull-to-refresh.

2023-07-12 07:57 UTC, merged