test(applets): added unit tests for refresh logic
ChildMindInstitute/mindlogger-app-refactor pull request #411
Opened 2023-10-10 13:41 UTC by DimitrySakalouski

2023-10-13 09:56 UTC, BamMironov requested changes

2023-10-13 09:56 UTC, BamMironov commented on src/entities/applet/model/services/RefreshService.test.js
> +}));
I get why `isAppOnline` and `onNetworkUnavailable` are mocked but the rest of them don't have to be mocked as they return simple JS readable data.

2023-10-18 10:08 UTC, anq83 requested changes

2023-10-18 10:08 UTC, anq83 commented on src/entities/applet/model/services/RefreshService.test.js
> +import { QueryClient } from '@tanstack/react-query';
Refresh service will be significally changed after merge PR:
https://github.com/ChildMindInstitute/mindlogger-app-refactor/pull/424

And with high probability it will be changed again after folowing task:
POC: Optimization based on appletVersion

So, maybe it worth to disable these tests and refrite/fix them afterall
@BamMironov  what do you think?

2024-03-11 09:38 UTC, anq83 commented
Checked the PR, it's not actual as RefreshService has been re-written to support aggregated (getting multiple details) endpoints.
It should be closed an not actual, without merge. @BamMironov

2024-03-11 09:40 UTC, closed without merging