Added logs for notifications and activity start/finish
ChildMindInstitute/mindlogger-app-refactor pull request #448
Opened 2023-10-27 12:22 UTC by vmkhitaryanscn

2023-10-27 12:27 UTC, anq83 requested changes
Follow the same logs format, add necessary id, names

2023-10-27 13:45 UTC, anq83 requested changes

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +              `[useStartEntity.startActivity]: Activity "${entityName}|${activityId}" restarted`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +              `[useStartEntity.startActivity]: Activity "${entityName}|${activityId}" resumed`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +          `[useStartEntity.startActivity]: Activity "${entityName}|${activityId}" started`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +              `[useStartEntity.startFlow]: Flow "${entityName}|${flowId}" restarted`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +              `[useStartEntity.startFlow]: Flow "${entityName}|${flowId}" resumed`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +          `[useStartEntity.startFlow]: Flow "${entityName}|${flowId}" started`,
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/widgets/survey/ui/Finish.tsx
> +    Logger.log(
Missed applet information

2023-10-27 13:45 UTC, anq83 commented on src/widgets/survey/ui/Intermediate.tsx
> +    Logger.log(
Missed applet information

2023-10-27 13:53 UTC, anq83 requested changes

2023-10-27 13:53 UTC, anq83 commented on src/widgets/survey/ui/Finish.tsx
> +      } ${logActivityName}|${activityId} completed`,
It seems the message is incorrect. We'd get: Flow [activity info] completed. If you're talking about flow then should be: Activity [activity info] within Flow [flow info] completed

2023-10-27 13:53 UTC, anq83 commented on src/widgets/survey/ui/Finish.tsx
> +      } ${logActivityName}|${activityId} completed`,
And the next message - Flow [flow info] completed

2023-10-27 13:53 UTC, anq83 commented on src/widgets/survey/ui/Finish.tsx
> +      } ${logActivityName}|${activityId} completed`,
Consider this for Intermediate screen as well

2023-10-27 13:53 UTC, anq83 commented on src/widgets/survey/ui/Intermediate.tsx
> +      } ${logActivityName}|${activityId} completed`,
Message is wrong. See comment for Finish screen

2023-10-30 11:33 UTC, anq83 requested changes

2023-10-30 11:33 UTC, anq83 commented on src/entities/applet/model/hooks/useStartEntity.ts
> +        logger.log(
Please clarify to Veronika, aren't these new logs sensitive user data like user actions (user events) that collected during activity execution?

2023-11-01 14:55 UTC, anq83 requested changes

2023-11-01 14:55 UTC, anq83 commented on src/shared/lib/alerts/permissionAlerts.ts
> +            '[permissionAlerts.onAlarmPermissionsDisabled] result: dismissed',
Is such data acceptable for write into logs?

2023-11-01 14:55 UTC, anq83 commented on src/widgets/survey/ui/Finish.tsx
> +      `[Finish.completeActivity]: Applet "${appletName}|${appletId}", Activity "${logActivityName}|${activityId}" completed`,
re-phrase, please

2023-11-01 14:55 UTC, anq83 commented on src/widgets/survey/ui/Intermediate.tsx
> +    if (flowId) {
flowId is always true in scope of Intermediate screen

2023-11-01 14:55 UTC, anq83 commented on src/widgets/survey/ui/Intermediate.tsx
> +    if (flowId) {
The same: flowId is always true here

2023-11-02 11:55 UTC, anq83 approved these changes

2023-11-02 11:55 UTC, anq83 commented on src/widgets/survey/ui/Intermediate.tsx
> +    Logger.log(
please, use nextActivity?.name / id

2023-11-02 11:57 UTC, anq83 requested changes
one minor fix to do

2023-11-02 11:57 UTC, BamMironov approved these changes

2023-11-03 10:24 UTC, anq83 approved these changes

2023-11-03 14:23 UTC, BamMironov commented on src/shared/lib/services/Logger.ts
> +    const deviceInfo = {
Please add a type here

2023-11-03 14:27 UTC, anq83 submitted a review, later dismissed

2023-11-03 14:27 UTC, anq83 commented on src/shared/lib/services/Logger.ts
> +      await this.onBeforeSendLogs();
Please move it below setBusy()

2023-11-09 14:46 UTC, BamMironov approved these changes

2023-11-09 15:00 UTC, mbarsukou approved these changes

2023-11-09 15:03 UTC, mbarsukou approved these changes

2023-11-09 15:06 UTC, mbarsukou approved these changes

2023-11-09 15:08 UTC, merged