Added applet details bottom tab bar, updated react-native-svg package…
ChildMindInstitute/mindlogger-app-refactor pull request #53
Opened 2023-02-08 13:31 UTC by vmkhitaryanscn

… version, added custom svg icons, refactor

2023-02-09 12:27 UTC, BamMironov requested changes

2023-02-09 12:27 UTC, BamMironov commented on src/screens/ui/AppletBottomTabNavigator.tsx
> +      screenOptions={appletDetailsScreenOptions as BottomTabNavigationOptions}>
Something went wring if you have to write "as BottomTabNavigationOptions"
Try creating appletDetailsScreenOptions using BottomTabNavigationOptions type

2023-02-15 07:01 UTC, BamMironov approved these changes

2023-02-15 10:45 UTC, anq83 approved these changes

2023-02-17 11:22 UTC, merged