Fixed M2-4361,M2-4377
ChildMindInstitute/mindlogger-app-refactor pull request #538
Opened 2023-12-13 12:11 UTC by vmkhitaryanscn

Fixed

[M2-4361](https://mindlogger.atlassian.net/browse/M2-4361)
[M2-4377](https://mindlogger.atlassian.net/browse/M2-4377)

[M2-4361]: https://mindlogger.atlassian.net/browse/M2-4361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-4377]: https://mindlogger.atlassian.net/browse/M2-4377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-13 12:20 UTC, anq83 approved these changes

2023-12-13 12:58 UTC, BamMironov requested changes

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/lib/hooks/useInProgressScreenNotifications.ts
> +export const useInProgressScreenNotifications = (
useInProgressScreenNotifications -> useUpcomingNotificationsObserver

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/lib/hooks/useInProgressScreenNotifications.ts
> +    NotificationManager.cancelUpcomingNotificationsForInProgressActivity(
cancelUpcomingNotificationsForInProgressActivity -> cancelUpcomingNotificationsForEventEntity

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/model/NotificationManager.ts
> +  async function cancelUpcomingNotificationsForInProgressActivity(
Please create a function called getNotificationsByEventId(eventId: string): LocalEventTriggerNotification[]

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/model/NotificationManager.ts
> +    interval: number,
Please use object instead of number. 

```
...
timeInterval: {
   from: number,
   to: number,
}
...
```

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/lib/hooks/useInProgressScreenNotifications.ts
> +    NotificationManager.cancelUpcomingNotificationsForInProgressActivity(
Better:

```
cancelNotificationForEventEntityInTimeInterval({
  entityId,
  eventId,
  timeInterval: { from: Date.now(), to: Date.now() + 20 },
});
```

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/lib/hooks/useInProgressScreenNotifications.ts
> +    NotificationManager.cancelUpcomingNotificationsForInProgressActivity(
Please add the check for foreground mode here

2023-12-13 12:58 UTC, BamMironov commented on src/entities/notification/lib/hooks/useInProgressScreenNotifications.ts
> +  }, [startInterval, stopInterval, eventId, entityId, isForeground]);
Please use two useEffects here. One for immediate function call and the other for setInterval start up.

2023-12-15 09:03 UTC, BamMironov requested changes

2023-12-15 09:03 UTC, BamMironov commented on src/screens/ui/InProgressActivityScreen.tsx
> +  useUpcomingNotificationsObserver(eventId, entityId);
If it's not a problem, could you add an empty line before useUpcomingNotificationsObserver?

2023-12-15 09:03 UTC, BamMironov commented on src/entities/notification/lib/hooks/useUpcomingNotificationsObserver.ts
> +  }, [startInterval, stopInterval, isForeground]);
Please create another `useEffect` that calls  `NotificationManager.cancelNotificationsForEventEntityInTimeInterval` immediately in the case when a notification is about to be displayed.

2023-12-18 11:34 UTC, BamMironov commented on src/entities/notification/lib/hooks/useUpcomingNotificationsObserver.ts
> +        { from: Date.now(), to: CHECK_INTERVAL },
Sorry. Yes, 
`const shouldCancel = timeInterval.from <= scheduledAt <= timeInterval.to;`
this should work perfectly

2023-12-18 14:40 UTC, BamMironov approved these changes

2023-12-18 14:44 UTC, merged