[WIP] test: unit tests to activity items
ChildMindInstitute/mindlogger-app-refactor pull request #565
Opened 2024-01-03 08:03 UTC by DimitrySakalouski

2024-01-03 08:04 UTC, DimitrySakalouski commented
https://mindlogger.atlassian.net/browse/M2-3996

2024-04-11 12:16 UTC, BamMironov requested changes
Please move mocks for third-party libraries to jest.setup.js. Apart from that, looks good to me

2024-04-11 12:16 UTC, BamMironov commented on src/shared/ui/survey/tests/AudioStimulusItem.test.tsx
> +);
Let's move it to jest.setup.js

2024-04-12 10:26 UTC, anq83 commented on src/shared/ui/survey/tests/AudioStimulusItem.test.tsx
> +}));
good point, done

2024-04-12 11:27 UTC, merged