M2-4928, M2-4929 Drawing and AbTrails streaming updates
ChildMindInstitute/mindlogger-app-refactor pull request #604
Opened 2024-01-31 17:57 UTC by vmkhitaryanscn

[M2-4928](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4928)
[M2-4929](https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-4929)

Added more information to drawing and abTrails to be sent over the socket

[M2-4928]: https://mindlogger.atlassian.net/browse/M2-4928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-4929]: https://mindlogger.atlassian.net/browse/M2-4929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-01 08:01 UTC, anq83 requested changes

2024-02-01 08:01 UTC, anq83 commented on src/entities/abTrail/ui/AbCanvas.tsx
> +      correct_path: `${currentNodeLabel} ~ ${nextNodeLabel}`,
I'd suggest to move details of creation the string into mapper layer, to make stream-point type more clear with simple primitive properties.

2024-02-01 08:10 UTC, anq83 requested changes

2024-02-01 08:10 UTC, anq83 commented on src/entities/abTrail/ui/AbCanvas.tsx
> +      streamEventPoint.actual_path = node.label;
the same - to separated function

2024-02-01 12:21 UTC, BamMironov commented on src/entities/abTrail/lib/types/test.ts
> +  actual_path: string;
@anq83 
That's the expected field names by the receivers of live events, I guess

2024-02-01 13:47 UTC, anq83 commented on src/entities/abTrail/lib/types/test.ts
> +  actual_path: string;
correct, they can only exist in DTO

2024-02-01 13:58 UTC, BamMironov requested changes

2024-02-01 14:14 UTC, anq83 requested changes

2024-02-01 14:14 UTC, anq83 commented on src/entities/abTrail/ui/AbCanvas.tsx
> +    onAddPointToStream(mapStreamEventToDto(createStreamEventPoint(point)));
Can we move mapStreamEventToDto ontide of the AB-related components?

2024-02-01 14:14 UTC, anq83 commented on src/entities/abTrail/ui/AbCanvas.tsx
> +      addOverRightPointToStream(point);
maybe addOverCorrectNextPointToStream?

2024-02-01 14:14 UTC, anq83 commented on src/entities/abTrail/ui/AbCanvas.tsx
> +      addOverRightPointToStream(point);
maybe addOverCorrectNextPointToStream or maybe addOverCorrectLastPointToStream?

2024-02-05 09:20 UTC, BamMironov approved these changes

2024-02-05 09:33 UTC, anq83 requested changes

2024-02-05 09:33 UTC, anq83 commented on src/features/pass-survey/ui/ActivityItem.tsx
> +    type as StreamEventActivityItemType,
is it safe to use as here?

2024-02-05 09:44 UTC, anq83 submitted a review, later dismissed

2024-02-05 09:44 UTC, anq83 commented on src/shared/lib/tcp/lib/streamEventMapper.ts
> +      );
It seems Flanker is missed

2024-02-06 08:29 UTC, BamMironov requested changes

2024-02-06 08:29 UTC, BamMironov commented on src/shared/lib/tcp/useSendLiveEvent.ts
> +      console.log(dataDto);
Please remove it

2024-02-07 12:37 UTC, BamMironov approved these changes

2024-02-13 11:00 UTC, merged