chore: changed login button behavior
ChildMindInstitute/mindlogger-app-refactor pull request #63
Opened 2023-02-17 12:40 UTC by DimitrySakalouski

2023-02-20 16:36 UTC, BamMironov requested changes

2023-02-21 07:25 UTC, DimitrySakalouski commented on src/shared/lib/hooks/useFormChanges.ts
> +      if (name && watchInputs.includes(name)) {
Let's keep tracking of what field was changed because of customer requirements, which where also implemented in legacy app

2023-02-21 15:51 UTC, BamMironov requested changes

2023-02-21 15:51 UTC, BamMironov commented on src/shared/lib/hooks/useFormChanges.ts
> +      if (name && watchInputs?.includes(name)) {
Please join these two if-statements

2023-02-22 11:02 UTC, DimitrySakalouski commented on src/shared/lib/hooks/useFormChanges.ts
> +      if (name && watchInputs?.includes(name)) {
Done

2023-02-22 11:11 UTC, BamMironov approved these changes

2023-02-22 11:12 UTC, merged