M2-5380: Conditional logic improvement
ChildMindInstitute/mindlogger-app-refactor pull request #634
Opened 2024-02-23 10:28 UTC by vmkhitaryanscn

### 📝 Description

🔗 [Jira Ticket M2-5380](https://mindlogger.atlassian.net/browse/M2-5380)

This PR adds optimizations for conditional logic
Calling `const currentStorageRecord = getCurrentActivityStorageRecord()!` on every iteration on bigger pipelines was causing lags.

This PR changes:
-  Conditional logic improvement

2024-02-26 15:56 UTC, farmerpaul approved these changes
I compared performance of progressing through questions of the Healthy Brain Network activities between `dev` and your PR, and it's definitely much faster in your PR – nice work! Code changes look sensible to me so I'll approve, however I think it would be wise for someone more familiar with the code to approve as well.

2024-02-27 10:54 UTC, BamMironov approved these changes
Looks much better than the previous implementation. Thanks

2024-02-27 13:35 UTC, anq83 requested changes

2024-02-27 13:35 UTC, anq83 commented on src/features/pass-survey/model/hooks/useActivityState.ts
> +  function removeConditionallyHiddenItemsAnswersAndTimers(fromStep: number) {
I like the idea to combile callback and iteratePipeline, but 
1. let's keep the previous name - iteratePipeline or iterateWithConditionalLogic
2. it seems this snippet is not considered:
```
if (!currentStorageRecord?.timers) {
   return;
}
```

2024-02-28 09:02 UTC, anq83 commented on src/features/pass-survey/model/hooks/useActivityState.ts
> +  function removeConditionallyHiddenItemsAnswersAndTimers(fromStep: number) {
2. yes, but not the same. In the prev. version it was just return, so {} wasn't recorder into the object unlike the current version. 
For example: !!undefined - false, !!{} - true.

2024-02-28 14:08 UTC, anq83 approved these changes

2024-02-29 10:03 UTC, merged