M2-7457:  Character Counter
ChildMindInstitute/mindlogger-app-refactor pull request #851
Opened 2024-08-26 20:46 UTC by felipeMetaLab

### 📝 Description
🔗 [Jira Ticket M2-#](https://mindlogger.atlassian.net/browse/M2-7457)
Creating CharacterCounter component and adding it to Paragraph text

Changes include:

- New component.
- implemented on paragraph

### 📸 Screenshots
![Simulator Screenshot - mindLogger - 2024-08-26 at 14 46 32](https://github.com/user-attachments/assets/4cceaedf-3a3c-499c-a836-7ced959e2147)
![Simulator Screenshot - mindLogger - 2024-08-26 at 14 46 27](https://github.com/user-attachments/assets/0bddb38e-90a7-48a8-8ace-e4f188894c7e)
![Simulator Screenshot - mindLogger - 2024-08-27 at 11 02 28](https://github.com/user-attachments/assets/c7b50e9a-3863-4885-b66a-0a8a158c3ad5)

### 🪤 Peer Testing
1 - crating a paragraph text
2 - the counter must appears on bottom right
3 - validate the color behavios when onFocus and onBlur
4 - validate the number of typed character and limit

2024-08-26 21:50 UTC, ChaconC requested changes

2024-08-26 21:50 UTC, ChaconC commented on src/shared/ui/survey/CharacterCounter.tsx
> +      {numberOfCharacters}/{limit} characters
Use translatable strings, example: `i18n.t('text_entry:character_count', { count, limit })`

2024-08-26 21:50 UTC, ChaconC commented on src/shared/ui/survey/ParagraphText.tsx
> +import CharacterCounter from './CharacterCounter';
import via `@shared/ui`

2024-08-26 21:50 UTC, ChaconC commented on src/shared/ui/survey/CharacterCounter.tsx
`CharacterCounter` is not an item type element, it shouldn't exist at the `src/shared/ui/survey` level.
Other similar elements, for example `BackButton` or `Input`, go in `src/shared/ui`

2024-08-26 21:50 UTC, ChaconC commented on src/shared/ui/CharacterCounterText.tsx
> +export default focusableInputHOC(CharacterCounterText);
why is this a `InputHOC`? This should be a label, as in not focusable

2024-08-26 21:50 UTC, ChaconC commented on src/shared/ui/survey/tests/CharacterCounter.test.tsx
Same here, should import from `@shared/ui`, this test should probably go in `src/shared/ui/tests`

2024-08-26 22:21 UTC, ChaconC commented on src/shared/ui/survey/CharacterCounter.tsx
> +type Props = {
add space between import and declarations

2024-08-27 10:46 UTC, BamMironov requested changes
Please consider a couple of comments from my side. But generally, it looks good to me

2024-08-27 10:46 UTC, BamMironov commented on src/shared/ui/CharacterCounter.tsx
> +      ]}
Please avoid using inline styles for Tamagui's components unless you have a good reason

2024-08-27 10:46 UTC, BamMironov commented on src/shared/ui/survey/ParagraphText.tsx
> +  const [characterCounter, setCharacterCounter] = useState(0);
I think you could use `value.length` instead

2024-08-27 10:46 UTC, BamMironov commented on src/shared/ui/CharacterCounter.tsx
In my opinion, it would be great to add validation against props here.
For instance, `limit` should not be a zero. Or `numberOfCharacters` should not exceed `limit`. 
If any of the check above fail then may be we should throw `Error` here, in the `CharacterCounter`'s render.

On the other hand, the validation can be performed somewhere else, e.g. in the parent component. However, the name "CharacterCounter" suggests us that it's the responsibility of the component to validate the incoming props.

2024-08-27 14:42 UTC, ChaconC commented on src/shared/ui/CharacterCounter.tsx
> +      {numberOfCharacters}/{limit} {t('character_counter:characters')}
`{numberOfCharacters}/{limit}` should be included as parameters of the string, as not all locales will follow the same "0/50 characters" convention

2024-08-27 14:47 UTC, BamMironov commented on src/shared/ui/CharacterCounter.tsx
Yeah, right. If the system should allow users to enter more characters than the `limit` value and highlight an error then the _numberOfCharacters <= limit_ validation should be omitted.

2024-08-27 19:08 UTC, felipeMetaLab commented on src/shared/ui/CharacterCounter.tsx
admin doesn't allow saving 0 or negative numbers

2024-08-27 20:06 UTC, BamMironov commented on src/shared/ui/CharacterCounter.tsx
If the efforts to throw an error are significant then of course it doesn't make sense.

Generally speaking, an independent system should not rely on the stability of the external system: the Admin Panel code has nothing to do with the Mobile App code. If something changes/breaks on the Admin Panel, the Mobile App won't know about it.

2024-08-27 20:45 UTC, ChaconC commented
@felipeMetaLab can you review the [failing test cases](https://github.com/ChildMindInstitute/mindlogger-app-refactor/actions/runs/10584356662/job/29328426256?pr=851)

2024-08-27 21:48 UTC, felipeMetaLab commented on src/shared/ui/CharacterCounter.tsx
I added some validations

2024-08-27 22:13 UTC, ChaconC commented on src/shared/ui/CharacterCounter.tsx
> +  WarnColor: {
`warnColor`

2024-08-27 22:21 UTC, ChaconC approved these changes
Ran tests locally and all is passing.
I'm fine as far as my comments, but curious for @BamMironov to take a final pass.

2024-08-27 23:37 UTC, felipeMetaLab commented
@BamMironov  I added some validations,  when you have a chance, can you validate again and check if every thing is good for you ? 
Thanks :)

2024-08-28 07:32 UTC, BamMironov commented
@felipeMetaLab The code looks great!

However, when I ran the app from your git branch to test the component I noticed that I was not able to enter more symbols than `limit`.


https://github.com/user-attachments/assets/422e31dc-5f84-4255-817f-873c06876b7f



According to **Acceptance Criteria 1** from [M2-7457](https://mindlogger.atlassian.net/browse/M2-7457):

**Given**: Respondent accesses Paragraph Text Item

**When**: The inputted text reaches the max characters limit set in the Admin Panel

**Then**: The respondent is still capable to enter any more symbols/ text to overflow the max character limit

**AND**
The text box enters into an error state, and respondent cannot move to next item

2024-08-28 16:28 UTC, felipeMetaLab commented
@BamMironov that's right, it is the normal behavior of paragraph, the fact is that the component "character counter" accepts more then the limit, we can force some fake limit in paragraph to test the character counter like the image I sent.

2024-08-28 20:56 UTC, BamMironov commented
@felipeMetaLab I am sorry but it seems I don't understand the point you have made. Please clarify: so you're saying that **Acceptance Criteria 1** is no longer relevant and you won't fix the current behaviour?

2024-08-28 20:59 UTC, BamMironov commented
@felipeMetaLab  I see, thanks! Okay, so if maxLength is relevant only for tablets please make sure to specify that in the ticket so that the QA team is aware.

2024-08-28 20:59 UTC, felipeMetaLab commented
No you are right @BamMironov  I was look at the criteria of the other paragraph ticket,  it had a limit implicit, but I noticed it changed, sorry.

2024-08-28 20:59 UTC, BamMironov approved these changes

2024-08-30 03:38 UTC, ChaconC commented on src/shared/ui/LongTextInput.tsx
> +    scrollEnabled: !!isTablet(),
Unnecessary double negation

2024-08-30 03:38 UTC, ChaconC commented on src/features/pass-survey/model/AnswerValidator.ts
> +          const numberOfCharacter = `${currentAnswer?.answer}`.length;
Add `answer` cast to `ParagraphTextResponse`
```suggestion
          const answer = currentAnswer?.answer as ParagraphTextResponse;
          const limit = currentPipelineItem.payload.maxLength;

          if (limit < answer.length) {
            return false;
          }
```

2024-08-30 03:39 UTC, ChaconC commented on src/features/pass-survey/model/AnswerValidator.ts
> +          }
Cast `answer` to `ParagraphTextResponse`, fits better with the established pattern in the rest of the validations.

```suggestion
          const answer = currentAnswer?.answer as ParagraphTextResponse;
          const limit = currentPipelineItem.payload.maxLength;

          if (limit < answer.length) {
            return false;
          }
```

2024-08-30 19:02 UTC, merged