Chore/M2-7771 improve encrypt and removing wait from use upload progress
ChildMindInstitute/mindlogger-app-refactor pull request #858
Opened 2024-09-16 16:55 UTC by felipeMetaLab

### 📝 Description

🔗 [Jira Ticket M2-7771](https://mindlogger.atlassian.net/browse/M2-7771)
in encrypt function  it was constantly using Buffer.concat.
By modifying  the function to collect encrypted chunks in an array and concatenating them once at the end we can improve the performance.
Removing the wait, we can improve even more the time.

Changes include:

- removing wait from the useUploadProgress
- improving encrypt function

### 🪤 Peer Testing

As long you already have the app properly configured, you must create an applet and test if the save flow is working properly and the time reduced for at least 1 second.

### ✏️ Notes
Before, the upload answers was taking about 1400 to 1600ms and encrypt was taking 1578 to 1650ms

2024-09-17 11:33 UTC, ChaconC requested changes
Can you share how you tested your results? Also including comparisons of before/after would be useful.

I added a simple timestamp around `encryptData()` and I'm not seeing any improvements
![CleanShot 2024-09-17 at 05 14 08](https://github.com/user-attachments/assets/0329b38c-9ed0-4133-86c0-5727ae7ca08e)

### Single Answer Applet
|Run|Time Before (ms)|Time After (ms)|
|-|-|-|
|1 | 3216 | 3225 |
|2 | 3130 | 3116 |
|3 | 3115 | 3221 |
|4 | 3117 | 3117 |

### Applet with 4 answers
|Run|Time Before (ms)|Time After (ms)|
|-|-|-|
|1 | 3123 | 3227 |
|2 | 3121 | 3121 |


Variation between runs looks within margin of error. The improved performance appears to be due to removing the `wait(delay)`, which probably should also remove the calls to `this.notifyAsync` from `UploadProgressObservable` and instead use `this.notify`

2024-09-17 11:33 UTC, ChaconC commented on src/shared/lib/hooks/useUploadProgress.ts
> -      await wait(delay);
You can remove `async` and `delay: number` since it's no longer used

2024-09-18 00:15 UTC, felipeMetaLab commented
I reverted to the old version of encryption.

2024-09-18 03:57 UTC, ChaconC approved these changes

2024-09-19 06:36 UTC, merged